dunder-mifflin-rails-review/config/routes.rb
Rails.application.routes.draw do
  resources :dogs
  resources :employees, except: :destroy
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

dunder-mifflin-rails-review/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

dunder-mifflin-rails-review/app/models/dog.rb
class Dog < ApplicationRecord
  has_many :employees
  has_many :owners, class_name: :Employee
end

dunder-mifflin-rails-review/app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :dog

  # validates :alias, uniqueness: true, presence: true
  # validates :title, uniqueness: true, presence: true

  validates_uniqueness_of :title, :alias, {case_sensitive: false}
  validates_presence_of :title, :alias

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

dunder-mifflin-rails-review/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

dunder-mifflin-rails-review/app/controllers/dogs_controller.rb
class DogsController < ApplicationController

  def index
    @dogs = Dog.all
  end

  def show
    @dog = Dog.find_by(id: params[:id])
  end
end

dunder-mifflin-rails-review/app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = Employee.all
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def new
    @errors = flash[:errors]
    @dogs = Dog.all
    @employee = Employee.new
  end

  def create
    employee = Employee.new(employee_params)

    if employee.valid?
      employee.save
      redirect_to employee
    else
      flash[:errors] = employee.errors.full_messages
      redirect_to new_employee_path
    end
  end

  private

  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :alias, :title, :office, :img_url, :dog_id)
  end
end

dunder-mifflin-rails-review/app/helpers/application_helper.rb
module ApplicationHelper
end

dunder-mifflin-rails-review/app/helpers/dogs_helper.rb
module DogsHelper
end

dunder-mifflin-rails-review/app/helpers/employees_helper.rb
module EmployeesHelper
end

dunder-mifflin-rails-review/app/views/dogs/index.erb
<h1>Dogs!</h1>

<% @dogs.each do |dog| %>
  <p><%= link_to dog.name, dog_path(dog) %></p>
<% end %>

dunder-mifflin-rails-review/app/views/dogs/show.erb
<h1><%= @dog.name %></h1>

<p>A <%= @dog.breed %>, a <%= @dog.age %>. Wiser than their years!</p>

<ul>
  <% @dog.employees.each do |employee| %>
    <li><%= employee.first_name %> - "<%= employee.alias %>"</li>
  <% end %>
</ul>

dunder-mifflin-rails-review/app/views/employees/index.erb
<h1>Employees</h1>

<% @employees.each do |employee| %>
  <p><%= link_to employee.first_name, employee %></p>
<% end %>

<%= link_to "Create New", new_employee_path %>

dunder-mifflin-rails-review/app/views/employees/new.erb
<h1>Create an Employee!</h1>

<% if @errors %>
  <% @errors.each do |error| %>
    <p><%= error %></p>
  <% end %>
<% end %>

<%= form_with model: @employee  do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <%= f.label :alias %>
  <%= f.text_field :alias %>
  <%= f.label :office %>
  <%= f.text_field :office %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :img_url %>
  <%= f.text_field :img_url %>
  <%= f.label :dog_id %>
  <%= f.collection_select(:dog_id, @dogs, :id, :name) %>
  <%= f.submit %>
<% end %>

dunder-mifflin-rails-review/app/views/employees/show.erb
<h1>Meet "<%= @employee.alias %>"</h1>

<% if @employee.img_url.length > 0 %>
  <%= image_tag(@employee.img_url, :alt => "picture of #{@employee.full_name} from The Office on NBC") %>
<% end %>

<h3><%= @employee.full_name %></h3>
<p><%= @employee.title %> at <%= @employee.office %></p>

<p>Currently owns the dog known as <%= link_to @employee.dog.name, @employee.dog %>.</p>

<%= link_to "Back to Employees", employees_path %>