whale-wishers-rails/config/routes.rb
Rails.application.routes.draw do
  resources :wishes
  resources :wishes, except: :destroy
  resources :whales, only: [:index, :show, :new, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "whales#index"

  resources :tags
end

whale-wishers-rails/app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_assignments
  has_many :wishes, through: :tag_assignments
end

whale-wishers-rails/app/models/tag_assignment.rb
class TagAssignment < ApplicationRecord
  belongs_to :wish
  belongs_to :tag
end

whale-wishers-rails/app/models/whale.rb
class Whale < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  validates :species, presence: true

  validate :size_multiple_of_a_thousand

  def size_multiple_of_a_thousand
    errors.add(:size, "must be a multiple of 1 thousand") if size % 1000 != 0
  end
end

whale-wishers-rails/app/models/wish.rb
class Wish < ApplicationRecord
  belongs_to :whale
  belongs_to :wisher, class_name: :Whale, optional: true
  has_many :tag_assignments
  has_many :tags, through: :tag_assignments
end

whale-wishers-rails/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def new
    @tag = Tag.new
  end

  def create
    Tag.create(params.require(:tag).permit(:name))
    redirect_to tags_path
  end

  def index
    @tags = Tag.all
  end
end

whale-wishers-rails/app/controllers/whales_controller.rb
class WhalesController < ApplicationController

  def index
    @whales = Whale.all
  end

  def show
    @whale = Whale.find_by(id: params[:id])
  end

  def new
    p flash[:errors]
    @whale = Whale.new
  end

  def create
    respond_to do |format|
      format.html
    end

    whale = Whale.new(params.require(:whale).permit(:name, :size, :species))

    if whale.save
      redirect_to "/whales"
    else
      flash[:errors] = whale.errors.full_messages
      flash[:name] = params[:whale][:name]
      flash[:size] = params[:whale][:size]
      flash[:species] = params[:whale][:species]
      # binding.pry
      redirect_to new_whale_path
    end
  end
end

whale-wishers-rails/app/controllers/wishes_controller.rb
class WishesController < ApplicationController
  def new
    @wish = Wish.new
    @whales = Whale.all
  end

  def create
    wish = Wish.new(params.require(:wish).permit(:title, :description, :whale_id))
    wish.save
    redirect_to wishes_path
  end

  def index
    @wishes = Wish.all
  end

  def show
    # @wish = Wish.find(params[:id])
    @wish = Wish.find_by(id: params[:id])

    if !@wish
      redirect_to wishes_path and return
    end

  end
end

whale-wishers-rails/app/helpers/whales_helper.rb
module WhalesHelper
end

whale-wishers-rails/app/helpers/wishes_helper.rb
module WishesHelper
end

whale-wishers-rails/app/views/tags/index.erb
<h1>Tags!</h1>

<%= @tags.each do |tag| %>
<% end %>

whale-wishers-rails/app/views/tags/new.erb
<%= form_with model: @tag do |f| %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

whale-wishers-rails/app/views/whales/index.erb
<h1>All of the Whales!</h1>

<% @whales.each do |whale| %>
  <%= link_to whale.name, whale %>
<% end %>

<%= link_to "Create New Whale", new_whale_path %>


<%= link_to "WISHES", wishes_path %>

whale-wishers-rails/app/views/whales/new.erb
<h1>Create a Whale!</h1>

<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <p style="color: red;"><%= error %></p>
  <%  end %>
<% end %>

<%= form_with model: @whale, remote: false do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, value: flash[:name] %>
  <%= f.label :size %>
  <%= f.number_field :size, value: flash[:size] %>
  <%= f.label :species %>
  <%= f.text_field :species, value: flash[:species] %>
  <%= f.submit %>

<% end %>

whale-wishers-rails/app/views/whales/show.erb
<h1>Hello! I'm <%= @whale.name %>.</h1

<p>FACTS ABOUT ME:</p>
<ul>
  <li>I am known as a "<%= @whale.species %>" whale.</li>
  <li>I am <%= @whale.size %> microwhales long! I am a whale measured in whales!</li>
</ul>

<%= link_to "Back to Whales", whales_path %>